Metrilus/MetriCam2

Jenkinsfile.groovy
Include MetriCam2.Controls in deployment so it can be used as a dependency for Framework builds.
Removed MetriCam2.Cameras.CameraTemplate from deployment.
=> Deploy MetriCam2.Controls, too.

Jenkinsfile.groovy
Orbbec is in the repo, but was not copied during deployment.
TheImagingSource is not contained in the repo.
(and sorted assemblies alphabetically)
=> Deploy Orbbec; not TheImagingSource

MetriCam2/Camera.cs
> @mischastik, @jangernert: Is das korrekt, diese Zuweisung aus dem try-Block rauszuziehen?
Nehmen wir an, bei `ChangeType` wuerde eine Exception fliegen. Dann wuerde ich erwarten, dass `isTypeConvertible` den Wert `false` bekommt.
`castedValue` hat dann allerdings den Wert `default(T)`, und das ist bei einem ValueType nicht `null`, also waere `isTypeConvertible` dann `true`.
New PR because
> Once a pull request is merged and closed, it is locked forever and cannot be reopened.
=> Revert 1 change from PR #8 as requested

BetaCameras/OrbbecOpenNI/OrbbecOpenNI.cpp, BetaCameras/OrbbecOpenNI/cmd.cpp, BetaCameras/OrbbecOpenNI/cmd.h
Change `get_cmos_params()` to return struct with error and calibration instead of just error. Also add parameter to avoid printing the calibration to stdout every time.
Use retrieved calibration if available and fall back to defaults on error.
=> OrbbecOpenNI: implement retrieving calibration directly from hardware

MetriCam2/Camera.cs, MetriCam2/CameraManagement.cs
Exclude Registry stuff from Camera and CameraManagement for .NET Standard 2.0 builds.
=> Make MetriCam2 .NET Standard 2.0 compatible

BetaCameras/OrbbecOpenNI/AssemblyInfo.cpp, BetaCameras/OrbbecOpenNI/OrbbecOpenNI.cpp, BetaCameras/OrbbecOpenNI/OrbbecOpenNI.h, BetaCameras/OrbbecOpenNI/cmd.cpp, BetaCameras/OrbbecOpenNI/cmd.h, SolutionAssemblyInfo.cs, SolutionAssemblyInfo.h
* Add VendorID and ProductID properties.
* Fix param-desc visibilities.
* Add param-descs for IRGain and IRExposure.
* Track value of irGain (closes #22).
* Improve Orbbec init sequence  
Fixes reconnect to same MetriCam2 object.
* Improve Orbbec.ActivateChannel  
Call SetIRGain only if needed.
* Fill ChannelName in Calc* methods
* Fill CameraSerial in Gettrinsics
=> Orbbec improvements

BetaCameras/OrbbecOpenNI/OrbbecOpenNI.cpp
Connect sometimes fails if the USB connection could not be initialized properly
=> Replace Exception by Warning in ConnectImpl

MetriCam2/Exceptions/ExceptionBuilder.cs
SocketException does not have a ctor with string parameter, so building that exception type resulted in a NullRefEx. Fallback is to neglect the actual exception type in such cases and include it in the message text.
=> Fix NullRefEx in ExceptionBuilder

BetaCameras/RealSense2/RealSense2.cs, BetaCameras/RealSense2/RealSense2.csproj, BetaCameras/RealSense2/RealSense2API.cs
- Don't stop pipeline twice on disposal
- Don't stop pipeline it it isn't already running
- Don't stop and restart pipeline on config changes if camera isn't connected yet
- Add call to retrieve firmware version from the camera (not actually used yet)
=> Realsense2 fixes

BetaCameras/RealSense2/RealSense2.cs, BetaCameras/RealSense2/RealSense2API.cs
Example:
```
RealSense2 camera = new RealSense2();
camera.Connect();
bool supported = camera.IsOptionSupported(RealSense2API.Option.BRIGHTNESS, RealSense2API.SensorName.COLOR);
camera.QueryOptionInfo(RealSense2API.Option.BRIGHTNESS, RealSense2API.SensorName.COLOR, out float min, out float max, out float step, out float def, out string desc);
float brightness = camera.GetOption(RealSense2API.Option.BRIGHTNESS, RealSense2API.SensorName.COLOR);
camera.SetOption(RealSense2API.Option.BRIGHTNESS, RealSense2API.SensorName.COLOR, brightness * 2);
```
=> Add API to get, set and query camera options

BetaCameras/RealSense2/RealSense2API.cs
Discussion:
The realsense2 API performs a version check upon context creation. If the major and minor versions don't match the ones from the realsense2 library the API-call fails. Even if the used API didn't change at all. Bug fix releases should be compatible. So version 2.8.0 all the way up to 2.8.3 are compatible.
Right now the realsense releases are pretty frequent. So should we just keep up with them and update our code accordingly or stick to a known to work version and advise all colleagues to use the specified version?
=> update RealSense2 API version to 2.9.0

BetaCameras/RealSense2/RealSense2.cs, BetaCameras/RealSense2/RealSense2API.cs
refactor static `PipelineRunning` to property of the pipeline struct to avoid issues with multiple cameras
=> Fix issue with multiple RealSense2 devices

BetaCameras/RealSense2/RealSense2API.cs
Calculating the color image broke with version 2.9.0. The official documentation doesn't state any relevant API changes. Retrieving the frame, reading the metadata and reading the first half of the image still works, so I don't think the issue is withing our code. I'm going to investigate this issue further and open up a bug report on the realsense project if necessary.
=> [RealSense2] Go back to version 2.8.3

BetaCameras/RealSense2/RealSense2.cs, BetaCameras/RealSense2/RealSense2API.cs
If no serial number was used to connect to a specific device, the serial of the connected device is queried and written to `MetriCam2.Camera.Serialnumber`.
This is helpful when using `CameraManagement.GetConnectableCameras` to list all available cameras, since now they can be identified by their serial number.
=> RealSense2: Get serialnumber of connected camera

BetaCameras/RealSense2/RealSense2.cs
fixes #67 
@f00f 
I wrote the patch before you opened #67
So instead of clearing in ConnectImpl, the cache is cleared in DisconnectImpl. 
This should have the same effect as far as I can see.
Commit messages should be squashed when merging =/
=> Realsense2 cache intrinsics

Jenkinsfile.groovy
Create debug builds as well.
This is helpful to quickly investigate a problem without having to check out and build a specific branch.
Automated builds of this branch have already successfully been used to step through some functions in the RealSense2 implementation.
Build time is a bit over a minute now. Compared to the <40s before.
=> Debug builds

BetaCameras/OrbbecOpenNI/OrbbecOpenNI.vcxproj
Using .props fixes build issues when reference checker is enabled
(also added a Win32 config line to be symmetric with all other build configs)
=> Orbbec project file: use .props

BetaCameras/BaslerToF/BaslerToF.cs, BetaCameras/BaslerToF/BaslerToF.csproj, BetaCameras/Sick.VisionaryT/VisionaryT.cs, BetaCameras/ifm/O3D3xx.cs, MetriCam2/Camera.cs
Dispose the `ToFCamera` object on Disconnect - and create it in Connect, not in the c'tor.
Rest is cleaning up stuff. I suggest going thru commit by commit, then the relevant stuff is easily recognizable.
=> Basler dispose camera

BetaCameras/RealSense2/RealSense2.cs
Save handle to device as member of the camera.
Otherwise when getting the 2 videoprofiles for the extrinsics
we'd have a different handle to the device for each profile.
This would cause an error when getting the extrinsics with the
message that no transformation between the two profiles is available.
=> [RealSense2] fix extrinsics

BetaCameras/RealSense2/RealSense2.cs
Workaround:
Open and start the depth sensor before querying Asic- or ProjectorTemperature.
This seems a bit counter-intuitive to me as using a pipeline should handle all the low level fiddling with sensors.
I opened up an [issue](https://github.com/IntelRealSense/librealsense/issues/1410) asking if the workaround is necessary or if it is indeed a bug in their software.
edit: the issue was clarified by an intel developer. Proper fix is implemented now.
=> [RealSense2] Workaround for temparture properties

BetaCameras/ifm/O3D3xx.cs
Minimize locked region, esp. move network receive out, to reduce wait time of in Update.
Now that I think about it ... maybe this introduces new race conditions and breaks stuff, because Update may be much faster now.
I've created a ticket with some more improvement ideas: #121
=> ifm: Faster Update

BetaCameras/RealSense2/RealSense2.cs
Unfortunately I still managed to make the MetriCam2 Settings UI misbehave when testing with the changes of #118.
It was possible for the `SettingsCombinationNotSupportedException` to only be thrown when already in the `finally` block. This leads to the `catch` block not being executed when it is thrown there and the property is not reset to it's old value. Then next time the pipeline tries to start it can't because the unsupported combination of settings is still applied.
Checking the config and throwing the exception before starting the pipeline in case of an invalid configuration fixes the problem.
=> [RealSense2] check realsense config before attempting to start the pipeline

BetaCameras/Kinect2/Kinect2.cs
The locks are no more required, since "enableImplicitThreadSafety=true" enforces entering the critical sections in Camera.CalcChannel.
Moreover, the hardcoded "cameraLock" usage obstructs freedom in derived classes
=> [Kinect2] Remove obsolete usage of "cameraLock" in Calc... methods

MetriCam2/CameraManagement.cs
`Assembly.LoadFile` requires an absolute path. Now, `ScanAssembly` can be called with just the assembly name and will succeed if the assembly is in the apps working dir.
=> Support loading cam assemblies from working folder

BetaCameras/Sick.VisionaryT/Device.cs, BetaCameras/Sick.VisionaryT/FrameData.cs
1. `ExceptionBuilder.Throw(ex.GetType()` would throw a `NullReferenceException`. Since `ExceptionBuilder` sucks anyways I chose to throw an exception straight.
1. The compile errors in `FrameData.cs` might be due to a stricter VS version, but they were bugs all the time.
=> Fix NRE and compile errors in Sick Visionary-T implementation

BetaCameras/BaslerToF/BaslerToF.cs, BetaCameras/RealSense/F200.cs, BetaCameras/RealSense/R200.cs, BetaCameras/SVS/SVS.cs, BetaCameras/Sick.TiM561/TiM561.cs, BetaCameras/Sick.VisionaryT/VisionaryT.cs, BetaCameras/TIVoxel/TIVoxel.cpp, BetaCameras/UEye/UEyeCamera.cs, BetaCameras/ifm/O3D3xx.cs, MetriCam2/Camera.cs, MetriCam2/Exceptions/ExceptionBuilder.cs, Tests/UnitTestParameterMechanism/Program.cs
I removed the obsolete `Throw` methods and replaced them with `throw Build`. The `Throw` methods were a bad idea in the first place for two reasons:
1. They obstruct the original location where the exception happened and compromised the stack trace.
2. They obfuscated the control flow. The compiler / intellisense could not recognize that an exception would be thrown and many places had to have an additional `return null` or similar.
=> Remove ExceptionBuilder.Throw methods

BetaCameras/OrbbecOpenNI/OrbbecOpenNI.cpp
The offset was applied in the wrong direction. Tested with current Astra Mini S cameras.
=> Orbbec: Fix offset bug between IR and Distance

BetaCameras/OrbbecOpenNI/OrbbecOpenNI.cpp, BetaCameras/OrbbecOpenNI/OrbbecOpenNI.h
Minor changes to Orbbec code.
Maybe in the future we could have collections of product IDs like
```csharp
List<int> SupportsOpenNIGain = new List<int> { ProductIDs.EmbeddedS, ProductIDs.StereoS };
```
I think that might become useful once we had multiple of those collections.
Or have a struct defining the relevant camera properties, e.g. the intensity offset.
Well, dreams...
=> Orbbec: Code clean up

BetaCameras/OrbbecOpenNI/MetriCam2.Orbbec.props, BetaCameras/OrbbecOpenNI/OrbbecOpenNI.vcxproj, Scripts/Jenkinsfile.groovy
The Orbbec project contained references to different versions of OpenNI.
I extracted the version number into a `.props` file to make the version within the project consistent.
The `.props` file is also deployed, so that projects using the Orbbec camera can import that file and copy the correct native binaries. Win!
Collateral:
I had to update `AdditionalLibraryPath` of the `x86` builds as these folders do not exist in the currently used OpenNI version. Might work or break the build, I don't know, but x86 is not a supported platform anyways.
=> Orbbec: Move OpenNI version into a deployed .props file

BetaCameras/Kinect2/Kinect2.csproj, BetaCameras/Kinect4Azure/Kinect4Azure.csproj, BetaCameras/Kinect4Azure/MetriCam2.Kinect4Azure.props, MetriCam2.Controls/MetriCam2.Controls.csproj, MetriCam2/MetriCam2.csproj, Scripts/Jenkinsfile.groovy
Build nuget packages for MetriCam2, MetriCam2.Controls, AzureKinect and Kinect for Windows v2.
Kinect for Windows v2 now uses the nuget reference instead of a local reference to `Z:\external-libraries`.
=> Build nuget packages

BetaCameras/BaslerACE/BaslerACE.csproj, BetaCameras/BaslerToF/BaslerToF.csproj, BetaCameras/Sick.VisionaryT/Sick.VisionaryT.csproj, BetaCameras/ifm/ifm.csproj, Scripts/Jenkinsfile.groovy
Remark: `ifm` and `Sick VisionaryT` do not have non-nuget dependencies, so we can push the packages to `nuget.org`
=> Create nuget packages for Basler{ACE,ToF}, ifm and Sick VisionaryT
