Tests/UnitTestParameterMechanism/Program.cs

More tests for the improvements from https://github.com/Metrilus/MetriCam2/pull/8

More tests for PR 8

---

BetaCameras/OrbbecOpenNI/OrbbecOpenNI.vcxproj

Use platform toolset v140 to be compatible with XnLib

Fix Orbbec build error

---

BetaCameras/OrbbecOpenNI/OrbbecOpenNI.cpp
BetaCameras/OrbbecOpenNI/OrbbecOpenNI.h
BetaCameras/OrbbecOpenNI/OrbbecOpenNI.vcxproj
BetaCameras/OrbbecOpenNI/cmd.cpp

1) New property IRFlooderEnabled
1) Status after Connect
* If any depth channel (ZImage or Point3DImage) is active then the Emitter will be on.
* The IR Flooder will be off.
1) Connect behaviour: attempts to connect to unknown S/N will throw ConnectionFailedException.
1) Build with VC++ 2015 toolset (fixes Jenkins build)

Support for Orbbec IR Flooder

---

MetriCam2/Camera.cs

Reduce output of GetParameters (issue 23)

---

BetaCameras/OrbbecOpenNI/OrbbecOpenNI.cpp
BetaCameras/OrbbecOpenNI/OrbbecOpenNI.h

ParamDesc behavior was broken by using Byte type

Fix Orbbec's IRGain property

---

MetriCam2/Camera.cs
MetriCam2/MetriCam2.NetStandard.csproj
MetriCam2/MetriCam2.csproj
MetriCam2/packages.config

Collection of changes to make MetriCam2 NET Standard 2.0 compatible.

Net standard compatibility

---

Jenkinsfile.groovy

Added RealSense2
Removed Orbbec (Astra SDK)
Removed RealSense (libRS1)

Update list of deployed assemblies

---

BetaCameras/SVS/SVS.cs

Use SVS LogLevel

---

BetaCameras/TIVoxel/TIVoxel.cpp

Only addresses our code, not external code which has > 100 warnings on its own.

TI Voxel: Fix compiler warnings

---

BetaCameras/SVS/SVS.cs

Some more improvements to the SVS log config.
This time all tested before I created the PR ;-)

SVS: improve log config

---

Jenkinsfile.groovy

use branch name as deploy folder and set commit status

Jenkinsfile CI preparation

---

Jenkinsfile.groovy
MetriCam2_SDK.sln
Scripts/Create Git Release Tag.bat
Scripts/Set Assembly-Info Version.cmd

* Use new folder structure
* Tag release builds
* Send mail on unstable or failure
* Add reference checking
* Use error checking in Publish stage
* Publish license file
* Use same pipeline stage names

Sync Jenkinsfile with that of Metrilus.Util

---

Jenkinsfile.groovy

Fixes #84 
Also direct straight to the build page from github instead to the flow graph.

Sanitize BUILD_URL

---

BetaCameras/OrbbecOpenNI/OrbbecOpenNI.vcxproj

All builds are broken, because I moved files.
This patch fixes all.
Once it's accepted, rebase all branches to master before launching further builds.

[minor] Update XnLib location

---

BetaCameras/BaslerToF/BaslerToF.cs
BetaCameras/RealSense2/RealSense2.cs
BetaCameras/SVS/SVS.cs
BetaCameras/Sick.TiM561/TiM561.cs
BetaCameras/TIVoxel/TIVoxel.cpp
BetaCameras/Xtion2/Xtion2.cs
BetaCameras/ifm/O3D3xx.cs
MetriCam2/Camera.cs

(includes patch from `update-xnlib-location` branch - should be merged thereafter)

Clean up model and vendor name props

---

BetaCameras/BaslerToF/BaslerToF.cs

This branch is to test and improve our support for Basler's multi-cam mode.
Please do not yet merge.
@schacs have fun :-)

BaslerToF: Fix multicam; add DeviceChannel

---

BetaCameras/BaslerToF/BaslerToF.cs

[BaslerToF] Ensure Update always delivers new data

---

BetaCameras/RealSense2/RealSense2.cs
MetriCam2.Controls/CameraConfigurationDialog.Designer.cs
MetriCam2.Controls/CameraConfigurationDialog.cs
MetriCam2.Controls/CameraSettingsControl.cs
MetriCam2.Controls/MultiFileSelector.cs

- crash fixes
- load builtin presets via GUI
- load custom presets via GUI
- redo layout of CameraConfigurationDialog

[RealSense2] Siemens fixes & improvements

---

BetaCameras/ifm/O3D3xx.cs

- fixes #121 
- use enum for modes
- double buffered raw data instead of calculating all images each iteration
- calculate images in CalcChannel instead of update loop
- refactoring

[Ifm] Improvements

---

BetaCameras/MatrixVision/MvBlueSirius.cpp
BetaCameras/MatrixVision/MvBlueSirius.h

Branch contains code from #114. So this should only be merged once #114 was merged.
This branch most importantly 
- fixes some crashes
- implements intrinsics for channels needed by MetriX
- fixes corrupt image data of depth channels

[MatrixVision] Improvements

---

BetaCameras/ifm/O3D3xx.cs

@stephenmartindale please review how I pass on the exception from the update loop to UpdateImpl (da40300). If you like also the rest.
@jangernert @mischastik please both review my changes

ifm: Improve timeout handling

---

BetaCameras/RealSense2/RealSense2.cs

Reimplement extrinsics and intrinsics cache in realsense2

---

BetaCameras/RealSense2/RealSense2.NetStandard.csproj
BetaCameras/RealSense2/RealSense2.cs
BetaCameras/RealSense2/RealSense2.csproj

Just keeping up with librealsense2 releases.
[Changelog](https://github.com/IntelRealSense/librealsense/wiki/Release-Notes)

Realsense 2.12.0

---

BetaCameras/ifm/O3D3xx.cs
BetaCameras/ifm/O3D3xxTriggerMode.cs
BetaCameras/ifm/ifm.csproj

Changes to ConnectSocket: connecting to hostname first involved a lengthy DNS query. If the hostname is an IP address we can connect to it directly. Makes connection really snappy :-)

ifm: Add TriggerMode, improve networking

---

BetaCameras/Sick.VisionaryT/Control.cs
BetaCameras/Sick.VisionaryT/VisionaryT.cs

I would not squash the commits

Sick: Don't stop streaming; allow reconnect

---

Samples/SimpleViewer/Properties/Settings.Designer.cs
Samples/SimpleViewer/Properties/Settings.settings
Samples/SimpleViewer/SimpleViewer.Designer.cs
Samples/SimpleViewer/SimpleViewer.cs
Samples/SimpleViewer/SimpleViewer.csproj
Samples/SimpleViewer/app.config

Annoying dependencies are the `MetriPrimitives` reference and Orbbec specific code.

Display current framerate in GUI and remove annoying dependencies.

---

BetaCameras/OrbbecOpenNI/OrbbecOpenNI.cpp
BetaCameras/OrbbecOpenNI/OrbbecOpenNI.vcxproj
BetaCameras/OrbbecOpenNI/OrbbecOpenNI.vcxproj.filters

Addresses several minor or exotic issues with Orbbec cameras.
I would **not squash** the commits.

Orbbec fixes

---

BetaCameras/WebCam/WebCam.h

[feature][WebCam] Added MirrorImage property.

---

BetaCameras/Kinect4Azure/Kinect4Azure.cs

Mostly trivial coding style changes.
`ConnectImpl` has "real" changes, please review those carefully. Thanks.

Azure Kinect: Clean up code

---

Changelog.md
MetriCam2_SDK.sln
README.md

Please merge #225 before merging this PR!

Release 16.0
